[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "v4.13.9"

[[repos.hooks]]
id = "commitizen"
stages = ["commit-msg"]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.24.2"

[[repos.hooks]]
id = "gitleaks"